### ISSUE TITLE
Broken in Firefox

### ISSUE THREAD

**Issue by bluepeter** [bluepeter/react-middle-ellipsis#3]

**Comment by bluepeter** [comment]
<img width="1678" alt="Screen Shot 2019-10-06 at 2 12 51 PM" src="https://user-images.githubusercontent.com/2158187/66276019-66ffbe00-e843-11e9-9243-ffcfe304c67d.png">

**Comment by BHznJNs** [comment]
It's still broken in firefox.
My firefox version is 149, under Windows 11 25h2

<img width="2240" height="2525" alt="Image" src="https://github.com/user-attachments/assets/52ccd65b-d41d-4273-a0e6-ea91481eb975" />
